# Generated by Django 4.2.11 on 2024-06-04 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='matchManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest1', models.CharField(max_length=80)),
                ('guest2', models.CharField(max_length=80)),
                ('guest3', models.CharField(max_length=80)),
                ('winner', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('tournement_id', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Primary_Player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
