# Generated by Django 4.2.11 on 2024-06-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='matchManager',
        ),
    ]
