# Generated by Django 4.2.11 on 2024-06-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_delete_matchmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user_score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
