# Generated by Django 4.2.11 on 2024-05-23 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Userdb', '__latest__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('RelationTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RelationTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserExtensionDB.relationtype')),
                ('User1Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Relation_user1', to=settings.AUTH_USER_MODEL)),
                ('User2Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Relation_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
