# Generated by Django 4.2.11 on 2024-05-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('StatusTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Name', models.CharField(max_length=80, unique=True)),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('Login42', models.CharField(max_length=80, unique=True)),
                ('Avatar', models.CharField(default='NULL', max_length=80)),
                ('Name_in_tournement', models.CharField(default='NULL', max_length=80)),
                ('Status_type_id', models.SmallIntegerField(default=0)),
                ('Admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('StatusTypeId', models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='Userdb.statustype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
