# Generated by Django 4.2.11 on 2024-05-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Admin',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Avatar',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Login42',
            new_name='login42',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Name_in_tournement',
            new_name='name_in_tournement',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='StatusTypeId',
            new_name='statusTypeId',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Status_type_id',
            new_name='status_type_id',
        ),
    ]
