# Generated by Django 4.2.11 on 2024-05-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(default='oui', max_length=100)),
                ('password', models.CharField(default='oui', max_length=100)),
                ('login42', models.CharField(default='oui', max_length=100)),
                ('photo', models.CharField(default='oui', max_length=100)),
                ('tournoiName', models.CharField(default='oui', max_length=100)),
                ('friends', models.CharField(default='oui', max_length=100)),
                ('matchHistoric', models.CharField(default='oui', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
