# Generated by Django 4.2.11 on 2024-05-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdb', '0002_user_delete_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login42',
        ),
        migrations.RemoveField(
            model_name='user',
            name='matchHistoric',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tournoiName',
        ),
        migrations.AddField(
            model_name='user',
            name='Avatar',
            field=models.CharField(default='tamere', max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='Name_in_tournement',
            field=models.CharField(default='tamere', max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='Status_type_id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.CharField(default='tamere', max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='Login42',
            field=models.CharField(default='tamere', max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(default='tamere', max_length=80),
        ),
    ]
