# Generated by Django 4.2.11 on 2024-05-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdb', '0005_remove_user_password_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Login42',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
