# Generated by Django 4.2.11 on 2024-05-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdb', '0006_alter_user_login42'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Admin',
            field=models.BooleanField(default=False),
        ),
    ]
