# Generated by Django 4.2.11 on 2024-05-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdb', '0007_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Staff',
            field=models.BooleanField(default=False),
        ),
    ]
