# Generated by Django 4.2.11 on 2024-05-23 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userdb', '0009_rename_staff_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='StatusTypeId',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='UserExtensionDB.statustype'),
        ),
    ]
