# Generated by Django 4.2.11 on 2024-05-23 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userdb', '0010_user_statustypeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('StatusTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='StatusTypeId',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='Userdb.statustype'),
        ),
    ]
