name: Makefile CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: CI tests
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: building docker app
      run: make test

    - name: test docker container run
      run: ./buildTest.sh